---
- hosts: localhost
  become: true
  become_method: sudo
  tasks:
    - name: install docker
      apt: name=docker.io state=present
    - name: installing java
      apt: name=default-jdk state=absent
